### ISSUE TITLE
Ubuntu Software / Snap Store is Unable to Update Itself

### ISSUE THREAD

**Issue by storyaddict** [canonical/snapcraft.io#4219]
I confirmed this issue is still present on a fresh install with an ISO downloaded on 9 March 2023

### Expected behaviour

When notified of updates to the snap store, click on the updates tab apply all updates.

### Steps to reproduce the problem

Install current ISO of Kinetic (22.10), check for updates normally. 
Ubuntu Software will notify you that the snap store has an update. Attempting to apply this update will fail since snap store is running.
Loop is created.

### Solution / Proposal

Solution/workaround I used:

kill snap store in either Terminal or System Monitor then run:

sudo snap refresh

**Possible Solution**

Have a bash script or something similar that is triggered when there is an update to the snap store to close the snap store, then prompt for password to update it.

**Comment by Lukewh** [comment]
Hi @storyaddict, this is the issue tracker for the snapcraft.io codebase. You'll want to report this on the Snap Store project itself [1]. It looks like your issue is similar to [2]. Thanks :).

[1] https://bugs.launchpad.net/snap-store-desktop
[2] https://bugs.launchpad.net/snap-store-desktop/+bug/1998233

**Comment by storyaddict** [comment]
Ah, perfect. Thanks for the correction. :)
