### ISSUE TITLE
snapcraft.io infinite redirect loop after login

### ISSUE THREAD

**Issue by Stehlampe2020** [canonical/snapcraft.io#4232]
### Expected behaviour   
The login page should get displayed.   

### Steps to reproduce the problem   
Go to snapcraft.io and click on "Sign in" in the top right.   

### Specs   
- _URL:_ [https://login.ubuntu.com/+openid, with changing GET parameters](https://login.ubuntu.com/+openid)   
- _Operating system:_ Ubuntu Unity 22.04 LTS   
- _Browser:_ Firefox 111.0.1 (64-bit) canonical - 1.0 (the non-snap version)   

### Behaviour observed   
The title of the page is "OpenID transaction in progress" and the page reloads every half to three seconds with slightly changing GET parameters. After a few minutes of looping the page would simply stop reloading and stay blank.   
I noticed this (as seen in the attached video) on Saturday, march 25, ~22:20. And yes, I tried disabling my adblocker, it changed nothing and as you can see there's also no "Blockerad av AdBlocker Ultimate" message in the "Överfört"-column, which would indicate adblocker intervention. 

https://user-images.githubusercontent.com/94976382/227744311-172fe31a-7647-4867-b585-c48930f1b653.mp4

**Comment by Stehlampe2020** [comment]
When going to login.ubuntu.com I was logged in normally, when I clicked on "Logout" it notified me that I might still be logged in on snapcraft.io, followed by the current date and then the login page displayed normally but I would enter that loop after logging in, login.ubuntu.com considered me logged in again as it just showed my account options.

**Comment by japikas** [comment]
Confirm the problem, facing the same issue, with old and new accounts by several people. Tested with Safari, Chrome, Firefox and Edge browsers in MacOS, Ubuntu Linux and Windows operating systems in ARM64 and x86 architectures.

**Comment by japikas** [comment]
Find a workaround. I created a new account Yesterday, but never managed to sign in and accept developer agreement, because of the above mentioned problem, when trying to sign in at snapcraft.io web site.
However, it is possible to sign in straight to the dashboard at https://dashboard.snapcraft.io where you can accept the developer agreement. After that the normal sign in at snapcraft.io works as expected.
This also solved my primary problem of not having a developer id. Now it is shown when executing 'snapcraft whoami'.

**Comment by Stehlampe2020** [comment]
Thanks for your extensive research!   
I still hope it gets fixed as new useer might not know this workaround, including me until I saw your comment...
