### ISSUE TITLE
Broken image in docs

### ISSUE THREAD

**Issue by bartaz** [canonical/snapcraft.io#4475]
### Steps to reproduce the problem

https://snapcraft.io/docs/installing-snap-on-manjaro-linux

<img width="1414" alt="image" src="https://github.com/canonical/snapcraft.io/assets/83575/86812be8-c663-44e0-81f0-002e7885460f">

If you click on the image name it opens a page with the image visible.

### Expected behaviour

Image should appear in the docs.

### Specs

- _URL:_ https://snapcraft.io/docs/installing-snap-on-manjaro-linux
- _Operating system:_ macOS
- _Browser:_ Chrome

**Comment by rsmelo92** [comment]
Hello, sorry for barging in, but this seems related to [this issue](https://github.com/canonical/ubuntu.com/issues/13436) I was investigating on ubuntu website repo (also [this one](https://github.com/canonical/ubuntu.com/issues/13417)), and after some research, it seems that the problem is related to [these lines here at canonicalwebteam.discourse](https://github.com/canonical/canonicalwebteam.discourse/blob/8a4c251c1d1d75d5f630269ea74bf8ec54fad7a9/canonicalwebteam/discourse/parsers/base_parser.py#L561-L565), as they are parsing the `img` tags that are coming via CMS wrongly, resulting in a broken link to the image `https://forum.snapcraft.io//forum-snapcraft-io.s3.dualstack.us-east-1.amazonaws.com (...)`, which should be `https://forum-snapcraft-io.s3.dualstack.us-east-1.amazonaws.com`

 I hit a wall, as this project is internal only, and I can't open a PR, so Im leaving this comment to try to at least give visibility to this probable error

Screenshots to be more precise:

<img width="1101" alt="image" src="https://github.com/canonical/snapcraft.io/assets/16295402/de576edb-70e7-4855-974d-66bca713c218">

<img width="1100" alt="image" src="https://github.com/canonical/snapcraft.io/assets/16295402/3df24211-4e21-4680-862a-28bc200ce40e">
